input("enter your name")
int(input("enter your age"))
num1=int(input("enter the first number"))
num2=int( input("enter the second number"))
c=(num1+num2)
d=(num1-num2)
e=(num1*num2)
f=(num1/num2)
print("the sum is",c)
print("the difference is",d)
print("the product is",e)
print("the divison is",d)